// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCY2gVawJk9OAv2mtxYGwncRmGokZLDqQ',
    appId: '1:360219018394:web:5c951e6025ce85681a4b23',
    messagingSenderId: '360219018394',
    projectId: 'lojavirtual-4227e',
    authDomain: 'lojavirtual-4227e.firebaseapp.com',
    storageBucket: 'lojavirtual-4227e.firebasestorage.app',
    measurementId: 'G-HXF9J8FTMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzzsMjVdYigSKg5u8KYU4m7mDIaIeGBbw',
    appId: '1:360219018394:android:c11c19da9b4b473b1a4b23',
    messagingSenderId: '360219018394',
    projectId: 'lojavirtual-4227e',
    storageBucket: 'lojavirtual-4227e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ5BCJRDRYzqrwqnD6ON2h6eI9-jiJtIU',
    appId: '1:360219018394:ios:03383253f04e0a521a4b23',
    messagingSenderId: '360219018394',
    projectId: 'lojavirtual-4227e',
    storageBucket: 'lojavirtual-4227e.firebasestorage.app',
    iosBundleId: 'com.lojavirtual.lojaVirtual',
  );
}
